# -*- coding: utf-8 -*-
"""Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aH_hWaX9g_C9PW6pGUL1nbK5hjuPSLrU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# **Tablulation**"""

url = 'https://api.covid19india.org/states_daily.json'

import urllib.request

urllib.request.urlretrieve(url, 'data.json')

covid_data = pd.read_json('data.json')

covid_data

import json

with open('data.json') as f:
  data = json.load(f)

data

data = data['states_daily']

data

covid_data = pd.json_normalize(data)

covid_data

df = covid_data

df.date = pd.to_datetime(df.date)

df

df = df[df['status'] == 'Confirmed'] #df = df[df.status == 'Confirmed']

df

df.drop(['status', 'dateymd'], axis=1, inplace=True)

df

df.set_index('date', inplace=True)

df

# df = df.replace('-', ' ', regex=True).astype(int)

df = df.apply(pd.to_numeric)

df

df.info()

"""# **Styling Tabulation**"""

df = df.tail(7)

df

def colour_red_negative(x):
  color = 'red' if x < 0 else 'white'
  return 'color: ' + color

df.style.applymap(colour_red_negative)  #applymap apply function to each cell

df.drop('un', axis=1, inplace=True)

df.style.highlight_max(color='red')

df.drop(['dd', 'ld'], axis=1, inplace=True)

df.style.highlight_max(color='red').highlight_min(color='green')

#dropping tt cuz it will affect the weightage of the whole dataset
df.drop('tt', axis=1, inplace=True)

def bold_max_value(x):
  is_max = (x == x.max())
  return ['font-weight: bold' if y else '' for y in is_max]

df.style.apply(bold_max_value)

