# -*- coding: utf-8 -*-
"""Agriculture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_qs__Q-UI-3FC7e21a29hqKSQpaXB8g
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('apy.csv', na_values="=")

df.dtypes

df.head()

df.State_Name.unique()

df.Crop_Year.unique()

df.Season.unique()

df.info()

pd.to_numeric(df.Production)

df['Production'].isnull().sum()

df.shape

df.dropna(inplace=True)

df.shape

sns.kdeplot(df['Production'])

sns.boxplot(df['Production'])

sns.boxplot(df['Area'])

sns.kdeplot(df['Area'])

df[df.State_Name == "Karnataka"]['District_Name'].unique()

df.groupby(['State_Name', 'Crop', 'Crop_Year']).sum()

df[df.State_Name == "West Bengal"]['Crop'].unique()

df.groupby(['State_Name', 'Crop_Year']).sum()

df_ = df.groupby(['State_Name', 'Crop_Year']).sum()

df_.reset_index(inplace=True)

df_.head()

df_[['State_Name', 'Crop_Year']].groupby('State_Name').count()

sns.lineplot(x="Crop_Year", y="Production", data=df[df.State_Name == "Tamil Nadu"]);

sns.lineplot(x="Crop_Year", y="Production", data=df, hue="State_Name");

!pip3 install plotly_express

import plotly_express as px

px.scatter(df_, x="Area", y="Production", animation_frame="Crop_Year", 
           animation_group="State_Name", color="State_Name")

df_.sort_values('Crop_Year', inplace=True)

df[(df.State_Name == "Kerala") & (df.Crop_Year == 2000)].sort_values('Production')

df_ = df[df.Crop.isin(['Rice', 'Wheat', 'Maize', 'Ragi'])].groupby(['State_Name', 'Crop_Year']).sum()

df_.reset_index(inplace=True)

df_.sort_values('Crop_Year', inplace=True)

px.scatter(df_, x="Area", y="Production", animation_frame="Crop_Year", 
           animation_group="State_Name", color="State_Name")

df_['Efficiency'] = df_['Production'] / df_['Area']

px.scatter(df_, x="Area", y="Efficiency", size="Production", animation_frame="Crop_Year", 
           animation_group="State_Name", color="State_Name", range_y = [0.75, 5], range_x=[-1E6, 20E6])

